"""Restore Backuparr media API exports after recreating users/libraries in the server.

Run without --apply first. The preview validates mappings without changing the
server. API keys are read from a file or the existing encrypted Backuparr config.
"""
import argparse
import base64
from collections import Counter, defaultdict
import json
from pathlib import Path
import sys
import zipfile

import requests

from apps.media_server import MediaServerError


# API-readable technical metadata is also useful for matching, but only these
# editable fields are replayed. Files/streams/IDs are regenerated by the scan.
EDITABLE_METADATA = {
    "Name", "OriginalTitle", "SortName", "Overview", "Genres", "Tags", "Studios",
    "People", "ProductionYear", "IndexNumber", "ParentIndexNumber", "ProviderIds",
    "CommunityRating", "CriticRating", "CustomRating", "OfficialRating",
    "PremiereDate", "EndDate", "LockedFields", "LockData", "ForcedSortName",
    "Taglines", "ProductionLocations", "PreferredMetadataCountryCode",
    "PreferredMetadataLanguage", "DisplayOrder", "AspectRatio", "Video3DFormat",
    "AlbumArtists", "ArtistItems", "Album", "Status", "AirDays", "AirTime",
    "AirsAfterSeasonNumber", "AirsBeforeEpisodeNumber", "AirsBeforeSeasonNumber",
}
USER_STATE = {"Played", "PlayCount", "PlaybackPositionTicks", "LastPlayedDate"}


class MediaRestore:
    def __init__(self, app, archive, path_maps=(), playlist_owners=None):
        self.app, self.archive = app, archive
        self.path_maps = sorted(path_maps, key=lambda pair: len(pair[0]), reverse=True)
        self.user_map, self.item_map = {}, {}
        self.actions = []
        self.planned = False
        self.playlist_owners = playlist_owners or {}

    def _json(self, name):
        return json.loads(self.archive.read(name))

    def _rows(self, name):
        with self.archive.open(name) as stream:
            for line in stream:
                if line.strip():
                    value = json.loads(line)
                    if not isinstance(value, dict):
                        raise MediaServerError("Invalid item in export")
                    yield value

    def _path(self, value):
        for old, new in self.path_maps:
            if value == old or value.startswith(old.rstrip("/\\") + "/") or value.startswith(old.rstrip("/\\") + "\\"):
                return new.rstrip("/\\") + value[len(old.rstrip("/\\")):]
        return value

    def _translate(self, value, field=""):
        if isinstance(value, str):
            reference = field.endswith(("Id", "Ids")) or field in {"EnabledFolders", "ExcludedSubFolders", "BlockedMediaFolders", "OrderedViews", "GroupedFolders", "LatestItemsExcludes", "MyMediaExcludes"}
            if reference:
                return self.user_map.get(value, self.item_map.get(value, self._path(value)))
            return self._path(value)
        if isinstance(value, list):
            return [self._translate(x, field) for x in value]
        if isinstance(value, dict):
            return {k: self._translate(v, k) for k, v in value.items()}
        return value

    def _action(self, section, method, path, **kwargs):
        self.actions.append((section, method, path, kwargs))

    def _match_items(self, old_items, current):
        paths, providers, names = defaultdict(set), defaultdict(set), defaultdict(set)
        for item in current:
            item_id = self.app._id(item['Id'])
            kind = item.get('Type')
            if item.get('Path'):
                paths[(kind, item['Path'])].add(item_id)
            for key, value in (item.get('ProviderIds') or {}).items():
                providers[(kind, key.lower(), str(value), item.get('ParentIndexNumber'), item.get('IndexNumber'))].add(item_id)
            names[(kind, item.get('Name'))].add(item_id)
        matched_targets = set()
        for item in old_items:
            old_id, kind = self.app._id(item['Id']), item.get('Type')
            found = paths.get((kind, self._path(item.get('Path', ''))), set())
            if not found:
                candidates = [providers[(kind, key.lower(), str(value), item.get('ParentIndexNumber'), item.get('IndexNumber'))]
                              for key, value in (item.get('ProviderIds') or {}).items()]
                candidates = [c for c in candidates if c]
                found = set.intersection(*candidates) if candidates else set()
            if not found and kind not in self.app.playable_types:
                found = names.get((kind, item.get('Name')), set())
            if len(found) != 1:
                raise MediaServerError(f"Cannot uniquely match {kind} {item.get('Name', old_id)!r}; recreate/scan it or supply --path-map before restoring")
            target_id = next(iter(found))
            if target_id in matched_targets:
                raise MediaServerError('Multiple source items match one target item; resolve the library mapping before restoring')
            matched_targets.add(target_id)
            self.item_map[old_id] = target_id

    def plan(self):
        self.actions.clear()
        self.planned = False
        manifest = self._json('manifest.json')
        if (manifest.get('format') != 'backuparr-media-api-export' or manifest.get('format_version') != 1
                or manifest.get('app') != self.app.name):
            raise MediaServerError('This archive is not a supported export for the selected application')
        if self.archive.testzip() is not None:
            raise MediaServerError('The export archive is corrupt')
        server, _ = self.app._settings()
        if server['Version'].split('.')[0] != manifest['server_version'].split('.')[0]:
            raise MediaServerError('Restore to the same major server version first')
        old_users, current_users = self._json('users.json'), self.app._users()
        for old in old_users:
            matches = [u for u in current_users if u.get('Name', '').casefold() == old.get('Name', '').casefold()]
            if len(matches) != 1:
                raise MediaServerError(f"Recreate user {old.get('Name')!r} with a new password before restoring")
            if old.get('HasPassword') and not matches[0].get('HasPassword'):
                raise MediaServerError(f"Set a password for user {old.get('Name')!r} before restoring their policy")
            self.user_map[self.app._id(old['Id'])] = self.app._id(matches[0]['Id'])
        old_items = list(self._rows('catalog.jsonl'))
        current_items = list(self.app._items())
        # Private playlists can appear only in a user's listing.
        all_old = {x['Id']: x for x in old_items}
        all_current = {x['Id']: x for x in current_items}
        for old in old_users:
            all_old.update({x['Id']: x for x in self._rows(f"user-items/{old['Id']}.jsonl")})
            all_current.update({x['Id']: x for x in self.app._items(self.user_map[old['Id']])})
        self._match_items(all_old.values(), all_current.values())
        names = set(self.archive.namelist())
        # Libraries must already exist so media has stable, discoverable target IDs.
        current_libraries = self.app._get('/Library/VirtualFolders', list)
        for old in self._json('libraries.json'):
            matches = [x for x in current_libraries if x.get('Name') == old.get('Name')]
            if len(matches) != 1:
                raise MediaServerError(f"Recreate and scan library {old.get('Name')!r} before restoring")
            target = self.app._id(matches[0].get('ItemId') or matches[0].get('Id'))
            old_library_id = old.get('ItemId') or old.get('Id')
            if old_library_id:
                self.item_map[self.app._id(old_library_id)] = target
            self._action('libraries', 'POST', '/Library/VirtualFolders/LibraryOptions', json={
                'Id': target, 'LibraryOptions': self._translate(old.get('LibraryOptions', {}))})
        installed = {p['Id'].lower() for p in self.app._get('/Plugins', list)}
        for filename in sorted(names):
            if filename.startswith('plugin-configuration/') and filename.endswith('.json'):
                plugin_id = self.app._id(Path(filename).stem)
                if plugin_id.lower() not in installed:
                    raise MediaServerError(f'Install the plugin with ID {plugin_id} before restoring')
                self._action('plugins', 'POST', f'/Plugins/{plugin_id}/Configuration', json=self._translate(self._json(filename)))
        for old in old_users:
            old_id, new_id = old['Id'], self.user_map[old['Id']]
            self._action('users', 'POST', f'/Users/{new_id}/Configuration', json=self._translate(old['Configuration']))
            self._action('user policies', 'POST', f'/Users/{new_id}/Policy', json=self._translate(old['Policy']))
            filename = f'display-preferences/{old_id}.json'
            if filename in names:
                self._action('preferences', 'POST', '/DisplayPreferences/usersettings', params={'UserId': new_id, 'Client': 'emby'}, json=self._translate(self._json(filename)))
            for item in self._rows(f'user-items/{old_id}.jsonl'):
                state = item.get('UserData')
                if not isinstance(state, dict):
                    continue
                new_item = self.item_map[item['Id']]
                # Container Played/PlayCount fields are derived from their children.
                if item.get('Type') in self.app.playable_types:
                    self._action('watch states', 'POST', f'/Users/{new_id}/Items/{new_item}/UserData',
                                 json={k: state[k] for k in USER_STATE if k in state})
                if 'Likes' in state:
                    liked = state['Likes']
                    self._action('ratings', 'DELETE' if liked is None else 'POST', f'/Users/{new_id}/Items/{new_item}/Rating',
                                 params={} if liked is None else {'Likes': str(liked).lower()})
                if 'IsFavorite' in state:
                    self._action('favorites', 'POST' if state['IsFavorite'] else 'DELETE', f'/Users/{new_id}/FavoriteItems/{new_item}')
            if f'user-images/{old_id}' in names:
                self._action('user images', 'POST', f'/Users/{new_id}/Images/Primary',
                             image_file=f'user-images/{old_id}', content_type=self._json(f'user-images/{old_id}.json')['content_type'])
        for old in sorted(all_old.values(), key=lambda i: {'Series': 0, 'Season': 1, 'MusicAlbum': 1}.get(i.get('Type'), 2)):
            if old.get('Type') in self.app.playable_types | {'Series', 'Season', 'MusicAlbum', 'MusicArtist', 'Playlist', 'BoxSet'}:
                new_id = self.item_map[old['Id']]
                body = {k: v for k, v in old.items() if k in EDITABLE_METADATA}
                body.update({'Id': new_id, 'Type': old.get('Type')})
                for key in ('Genres', 'Tags', 'Studios', 'People', 'Taglines', 'LockedFields'):
                    body.setdefault(key, [])
                body.setdefault('ProviderIds', {})
                self._action('metadata', 'POST', f'/Items/{new_id}', json=body)
        processed = set()
        for filename in sorted(names):
            if filename.startswith('memberships/') and filename.endswith('.jsonl'):
                _, old_user, leaf = filename.split('/')
                old_id = self.app._id(leaf[:-6])
                if old_id in processed:
                    continue  # Shared playlists/collections are rebuilt once.
                processed.add(old_id)
                new_id, new_user = self.item_map[old_id], self.user_map[old_user]
                members = [self.item_map[x['Id']] for x in self._rows(filename)]
                if all_old[old_id]['Type'] == 'Playlist':
                    owner = self.playlist_owners.get(old_id)
                    candidates = [u for u in old_users if (u.get('Name', '').casefold() == owner.casefold() if owner else u['Policy'].get('IsAdministrator'))]
                    if len(candidates) != 1:
                        raise MediaServerError(f'Specify --playlist-owner {old_id}=USER_NAME for this playlist')
                    new_user = self.user_map[candidates[0]['Id']]
                    existing = list(self.app._items(new_user, path=f'/Playlists/{new_id}/Items', playlist=True))
                    entry_ids = [self.app._id(x['PlaylistItemId']) for x in existing]
                    if entry_ids:
                        self._action('playlists', 'DELETE', f'/Playlists/{new_id}/Items', params={'EntryIds': ','.join(entry_ids), 'UserId': new_user})
                    # One request per entry preserves intentional duplicates on both servers.
                    for member in members:
                        self._action('playlists', 'POST', f'/Playlists/{new_id}/Items', params={'Ids': member, 'UserId': new_user})
                else:
                    existing = list(self.app._items(new_user, ParentId=new_id, Recursive='false'))
                    if existing:
                        self._action('collections', 'DELETE', f'/Collections/{new_id}/Items', params={'Ids': ','.join(x['Id'] for x in existing)})
                    if members:
                        self._action('collections', 'POST', f'/Collections/{new_id}/Items', params={'Ids': ','.join(members)})
            if filename.startswith('images/') and filename.endswith('/index.json'):
                old_id = self.app._id(filename.split('/')[1]);new_id = self.item_map[old_id]
                images = self._json(filename)
                existing = self.app._get(f'/Items/{new_id}/Images', list)
                types = {i['ImageType'] for i in images}
                for image in sorted(existing, key=lambda i: i.get('ImageIndex', 0), reverse=True):
                    if image['ImageType'] in types:
                        self._action('artwork', 'DELETE', f"/Items/{new_id}/Images/{self.app._id(image['ImageType'])}/{int(image.get('ImageIndex', 0))}")
                for image in sorted(images, key=lambda i: (i['ImageType'], i.get('ImageIndex', 0))):
                    self._action('artwork', 'POST', f"/Items/{new_id}/Images/{self.app._id(image['ImageType'])}", image_file=image['ExportFile'], content_type=image['ContentType'])
        if 'scheduled-tasks.json' in names:
            tasks = {t.get('Key'): t for t in self.app._get('/ScheduledTasks', list)}
            for task in self._json('scheduled-tasks.json'):
                key = task.get('Key')
                if key not in tasks:
                    raise MediaServerError(f'Reinstall the component providing scheduled task {key!r}')
                self._action('task triggers', 'POST', f"/ScheduledTasks/{self.app._id(tasks[key]['Id'])}/Triggers", json=task.get('Triggers', []))
        # Reapply core/named configuration last; network changes may require a restart.
        self._action('server settings', 'POST', '/System/Configuration', json=self._translate(self._json('system-configuration.json')))
        for filename in sorted(names, key=lambda n: n == 'configuration/network.json'):
            if filename.startswith('configuration/') and filename.endswith('.json'):
                key = self.app._id(Path(filename).stem)
                self._action('named settings', 'POST', f'/System/Configuration/{key}', json=self._translate(self._json(filename)))
        self.planned = True
        return dict(Counter(action[0] for action in self.actions))

    def apply(self):
        if not self.planned:
            raise MediaServerError("Complete a successful preview before applying a restore")
        self.planned = False
        completed = Counter()
        for section, method, path, kwargs in self.actions:
            kwargs = dict(kwargs)
            if 'image_file' in kwargs:
                kwargs['data'] = base64.b64encode(self.archive.read(kwargs.pop('image_file')))
                kwargs['headers'] = {'Content-Type': kwargs.pop('content_type')}
            try:
                response = self.app.session.request(method, self.app.url + path, timeout=self.app.timeout, allow_redirects=False, **kwargs)
            except requests.RequestException:
                raise MediaServerError(f'Restore interrupted during {section}; completed {sum(completed.values())} actions. Check the server before retrying.') from None
            with response:
                if response.status_code not in (200, 201, 204):
                    raise MediaServerError(f'Restore stopped during {section} (HTTP {response.status_code}); completed {sum(completed.values())} actions. No automatic rollback.')
            completed[section] += 1
        return dict(completed)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('archive', type=Path)
    parser.add_argument('--url', help='Target server URL; defaults to the saved app configuration')
    parser.add_argument('--key-file', type=Path, help='File containing the target administrator API key')
    parser.add_argument('--path-map', action='append', default=[], metavar='OLD=NEW', help='Map media path prefixes when moving servers')
    parser.add_argument('--playlist-owner', action='append', default=[], metavar='OLD_ID=USER_NAME', help='User allowed to edit a playlist; defaults to the sole administrator')
    parser.add_argument('--apply', action='store_true', help='Apply the validated plan, overwriting the listed settings/data')
    args = parser.parse_args(argv)
    try:
        from backup import build_app
        from config_store import load_config
        with zipfile.ZipFile(args.archive) as archive:
            manifest = json.loads(archive.read('manifest.json'))
            name = manifest.get('app')
            if name not in ('jellyfin', 'emby'):
                raise MediaServerError('Expected a Jellyfin or Emby API export')
            cfg = load_config()['apps'].get(name, {}).copy()
            if args.url:
                cfg['url'] = args.url
            if args.key_file:
                cfg['api_key'] = args.key_file.read_text().strip()
            app = build_app(name, cfg)
            mappings = []
            for value in args.path_map:
                old, separator, new = value.partition('=')
                if not separator or not old or not new:
                    raise MediaServerError('--path-map must be OLD=NEW with nonempty paths')
                mappings.append((old, new))
            owners = {}
            for value in args.playlist_owner:
                old_id, separator, username = value.partition('=')
                if not separator or not username:
                    raise MediaServerError('--playlist-owner must be OLD_ID=USER_NAME')
                owners[app._id(old_id)] = username
            restore = MediaRestore(app, archive, mappings, owners)
            plan = restore.plan()
            print(json.dumps({'plan': plan, 'applied': False}, indent=2))
            if args.apply:
                print(json.dumps({'completed': restore.apply(), 'applied': True, 'restart_may_be_required': True}, indent=2))
            else:
                print('Preview only. Re-run with --apply after reviewing the plan.')
    except (MediaServerError, OSError, ValueError, KeyError, zipfile.BadZipFile) as exc:
        print(f'Restore failed: {exc}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
